<?php
/**
 * FileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * File-Microservice SDK
 *
 * SDK to interact with File Microservice
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: yuset.calzadilla@giffits.de
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.2-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FileApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addFile
     *
     * Add a new file to the filesystem.
     *
     */
    public function testAddFile()
    {
    }

    /**
     * Test case for deleteFile
     *
     * Deletes a file.
     *
     */
    public function testDeleteFile()
    {
    }

    /**
     * Test case for downloadFile
     *
     * Download a file with a specific id.
     *
     */
    public function testDownloadFile()
    {
    }

    /**
     * Test case for findAllFiles
     *
     * Get all files.
     *
     */
    public function testFindAllFiles()
    {
    }

    /**
     * Test case for findFileById
     *
     * Get file by ID.
     *
     */
    public function testFindFileById()
    {
    }

    /**
     * Test case for patchFile
     *
     * Patch a specific file from the filesystem.
     *
     */
    public function testPatchFile()
    {
    }

    /**
     * Test case for updateFile
     *
     * Update a specific file from the filesystem.
     *
     */
    public function testUpdateFile()
    {
    }
}
