<?php
/**
 * FileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* File-Microservice SDK
 *
* SDK to interact with File Microservice
 *
* OpenAPI spec version: 1.0.0-oas3
 * Contact: yuset.calzadilla@giffits.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * FileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addFile
     *
     * Add a new file to the filesystem.
     *
     */
    public function testAddFile()
    {
    }

    /**
     * Test case for deleteFile
     *
     * Deletes a file.
     *
     */
    public function testDeleteFile()
    {
    }

    /**
     * Test case for downloadFile
     *
     * Download a file with a specific id.
     *
     */
    public function testDownloadFile()
    {
    }

    /**
     * Test case for findAllFiles
     *
     * Get all files.
     *
     */
    public function testFindAllFiles()
    {
    }

    /**
     * Test case for findFileById
     *
     * Get file by ID.
     *
     */
    public function testFindFileById()
    {
    }

    /**
     * Test case for patchFile
     *
     * Patch a specific file from the filesystem.
     *
     */
    public function testPatchFile()
    {
    }

    /**
     * Test case for updateFile
     *
     * Update a specific file from the filesystem.
     *
     */
    public function testUpdateFile()
    {
    }
}
