<?php
/**
 * SearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * File-Microservice SDK
 *
 * SDK to interact with File Microservice
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: yuset.calzadilla@giffits.de
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.2-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for searchByKeyMetadata
     *
     * Search file by metadata key.
     *
     */
    public function testSearchByKeyMetadata()
    {
    }

    /**
     * Test case for searchFileByMetadata
     *
     * Search file by metadata key and value.
     *
     */
    public function testSearchFileByMetadata()
    {
    }

    /**
     * Test case for searchFileByMultipleMetadata
     *
     * Search file by multiple metadata passed as json.
     *
     */
    public function testSearchFileByMultipleMetadata()
    {
    }
}
